### ISSUE TITLE
How do you disable fsprotect?

### ISSUE THREAD

**Issue by Muzim-the-Wise** [sharhalakis/fsprotect#10]
Hi.
Thing is working out good for me until I wanted to disable it. And I can't find anywhere info about how to disable it.

**Comment by Muzim-the-Wise** [comment]
You need to add nofsprotect in etc/default/grub through console in recovery mode.

**Comment by sharhalakis** [comment]
You can also pass nofsprotect as a kernel parameter using edit in the grub menu while booting.
