### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by ghost** [sharhalakis/fsprotect#6]

**Comment by Lucapz** [comment]
Yeah . I've got the same with Ubuntu 18.04 LTS  , loads of systemd-remount-fs.service fails. :(

01:53:02 systemd: Failed to start Remount Root and Kernel File Systems.
01:53:01 kernel: /bin/mount for / exited with exit status 32.
01:53:01 systemd: Failed to start Remount Root and Kernel File Systems.
01:52:59 kernel: /bin/mount for / exited with exit status 32.
01:52:43 kernel: aufs au_opts_parse:1247:mount[342]: unknown option errors=remount-ro
01:52:43 kernel: aufs au_opts_parse:1247:mount[342]: unknown option errors=remount-ro
01:52:43 kernel: aufs au_opts_parse:1247:mount[329]: unknown option errors=remount-ro
01:52:39 systemd: Failed to start Remount Root and Kernel File Systems.
01:52:38 kernel: aufs au_opts_parse:1247:mount[301]: unknown option errors=remount-ro
01:52:38 systemd-remount: /bin/mount for / exited with exit status 32.

and at shutdown

Failed Unmounting fsprotect/tmp
Failed Unmounting fsprotect/system
